---
title: "uso-tipos-chatbots-docentes"
author: "JJ Merelo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)

frecuencias_data <- read.csv("../data/chatbots-uso-docentes.csv", header = TRUE, na.strings="", sep = ";")

columnas <- strsplit("ChatGPT;Claude;Copilot;DeepSeek;Gemini;NotebookLM;Perplexity", ";")
resultados_uso <- data.frame( chatbot=character(),
                              frecuencia=character(),
                              porcentaje = numeric() );

for ( i in columnas[[1]] ) {
  frecuencias_uso_data  <-  data.frame(Disciplina = frecuencias_data$Disciplina,
                                       frecuencias_data[i])

  porcentajes_data <-  frecuencias_uso_data %>% group_by(.data[[i]]) %>% summarise(Número = n()) %>%
    mutate(Proporción = Número / sum(Número))

  porcentajes_data$Frecuencia <- factor(porcentajes_data[[i]],
                                      levels = c("No lo conozco",
                                                 "Lo conozco pero no lo he usado",
                                                 "Lo uso en el conexto universitario",
                                                 "Lo uso tanto en el conexto universitario como para otras tareas",
                                                 "Lo uso para otras tareas" )
                                      )
  porcentajes_data <- porcentajes_data %>%
    filter(!is.na(Frecuencia))

  for (j in levels(porcentajes_data$Frecuencia) ) {
    resultados_uso <- rbind( resultados_uso,
                             data.frame( chatbot = i,
                                         frecuencia = j,
                                         porcentaje = sum( porcentajes_data$Proporción[porcentajes_data$Frecuencia == j] )
                             )
    )
  }

}


```

Now the chart

```{r grafico, echo=FALSE, message=FALSE, warning=FALSE}

resultados_uso$chatbot <- factor(resultados_uso$chatbot,
                             levels = resultados_uso %>%
                               filter(frecuencia == "Lo uso tanto en el conexto universitario como para otras tareas") %>%
                               arrange(porcentaje) %>% pull(chatbot)
)
ggplot(resultados_uso, aes(x=chatbot, fill=frecuencia, y = porcentaje)) +
    geom_bar( stat="identity", position="dodge") +
    labs(title=paste0("Frecuencia de uso ",i), x="Frecuencia", y="Proporción") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

And now the table

```{r tabla, echo=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
resultados_uso %>%
  pivot_wider(names_from = frecuencia, values_from = porcentaje) %>%
  arrange(desc(`Lo uso tanto en el conexto universitario como para otras tareas`)) %>%
  kable( digits=3,
         col.names = c("Chatbot",
                       "Don't know it",
                       "I know it, I've never used it",
                        "Used it in academic context",
                        "Used it in academic and other contexts",
                        "Used it only outside the academic context" ),
         caption = "What specific chatbots have teachers used?",
  ) %>%
  kable_styling( full_width = FALSE )
```
