---
title: "uso-chatbots-docentes"
author: "JJ Merelo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup,  echo=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)

frecuencias_data <- read.csv("../data/frecuencias.csv", header = TRUE, sep = ";")

porcentajes_data <-  frecuencias_data %>% group_by(Disciplina,Frecuencia) %>%
  summarise(Número = n()) %>%
  mutate(Proporción = Número / sum(Número))
porcentajes_data$Disciplina <- factor(porcentajes_data$Disciplina,
                                      levels = c("FFL",
                                                 "TIC",
                                                 "Otras")
                                      )
porcentajes_data$Discipline <- recode(porcentajes_data$Disciplina,
                                        "FFL" = "Languages",
                                        "TIC" = "IT",
                                        "Otras" = "Others"
                                        )
porcentajes_data$Frecuencia <- factor(porcentajes_data$Frecuencia,
                                      levels = c("Nunca", "Casi nunca", "A veces", "Casi siempre", "Siempre"))
porcentajes_data$Frequency <- recode(porcentajes_data$Frecuencia,
                                      "Nunca" = "Never",
                                      "Casi nunca" = "Almost never",
                                      "A veces" = "Sometimes",
                                      "Casi siempre" = "Almost always",
                                      "Siempre" = "Always"
                                      )
ggplot(porcentajes_data, aes(x=Frequency, fill=Discipline, y = Proporción)) +
  geom_bar( stat="identity", position="dodge") +
  labs(title="How often is it used", x="Frequency", y="Proportion") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

The same data in a table

```{r tabla, echo=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)

porcentajes_data$Likert <- recode(porcentajes_data$Frecuencia,
                                      "Nunca" = 0,
                                      "Casi nunca" = 1,
                                      "A veces" = 2,
                                      "Casi siempre" = 3,
                                      "Siempre" = 4
                                      )

promedio_data <- porcentajes_data %>% group_by(Discipline) %>%
    summarise(Average = sum(Likert * Número) / sum(Número),
              SD = sqrt( sum( Número * (Likert - (sum(Likert * Número) / sum(Número)))^2 ) / sum(Número) )
              )

porcentajes_data %>%
  pivot_wider(names_from = Frecuencia, values_from = Número, id_cols = Discipline) -> tabla_frecuencias

tabla_frecuencias <- tabla_frecuencias[,c(1,5,3,2,4,6)] 

kable( tabla_frecuencias,
         col.names = c("Discipline", "Never", "Almost never","Sometimes","Almost always","Always"),
         caption = "How often is it used",
  ) %>%
  kable_styling( full_width = FALSE )
```
